### ISSUE TITLE
Access denied finding property persist.vendor.audio fx.current

### ISSUE THREAD

**Issue by diaconori** [ImnIrdst/iiVisu#24]
Getting the following error: Access denied finding property persist.vendor.audio fx.current, despite allowing access to audio recording.

**Comment by diaconori** [comment]
E/libc: Access denied finding property "persist.vendor.audio_fx.current"
W/diaco.nori: type=1400 audit(0.0:11205): avc: denied { read } for name="u:object_r:vendor_mot_audio_fx_prop:s0" dev="tmpfs" ino=2876 scontext=u:r:untrusted_app:s0:c62,c257,c512,c768 tcontext=u:object_r:vendor_mot_audio_fx_prop:s0 tclass=file permissive=0 app=com.diaconori.recorder

**Comment by diaconori** [comment]
I am using a Motorola device. Not sure if it is OEM related. If that's the case then that's obviously not because of your library. I've tested it on a pixel phone and on a nexus tablet. It works there. Please get back to me on this issue.

**Comment by ImnIrdst** [comment]
Sorry, I don't have this device to test on It. You can send me a PR If you fixed this bug.

**Comment by diaconori** [comment]
The bug was not related to your visualizer library. It is an error that pops up whenever the WaveRecorder wants to access the amplitude values of the phone's microphone. So I closed the issue :)
