### ISSUE TITLE
Width of wave for 1 second recording

### ISSUE THREAD

**Issue by ishyian** [ImnIrdst/iiVisu#25]
I need to draw a timeline under a waveform, how can I calculate width of one second part of wave?

**Comment by ImnIrdst** [comment]
Thanks for the question. I have updated the documentation in #32.

You can use the `tickDuration` parameter to calculate the width of one second. Here are some code snippets that might help:

https://github.com/ImnIrdst/iiVisu/blob/12ae01ebe0ee4fc72b90990fd705a1c43177e0d5/iivisu/src/main/java/com/imn/iivisu/RecorderVisualizer.kt#L25

https://github.com/ImnIrdst/iiVisu/blob/12ae01ebe0ee4fc72b90990fd705a1c43177e0d5/app/src/main/java/com/imn/ivisusample/recorder/Recorder.kt#L57
